---
title: R Notebook HICP and Consumption share
---
```{r}
#install.packages('ecb')

#### Data from ECB ####
rm(list=ls())
library(ecb)
library(ggplot2)
library(reshape2)
library(dplyr)
library(tidyverse)
```
LOAD DATA from ECB SDW
```{r}
names<-list("ICP.M.FR.N.000000.4.INX", "ICP.M.FR.N.010000.4.INX", "ICP.M.FR.N.020000.4.INX", "ICP.M.FR.N.030000.4.INX", "ICP.M.FR.N.040000.4.INX",	"ICP.M.FR.N.050000.4.INX", "ICP.M.FR.N.060000.4.INX", "ICP.M.FR.N.070000.4.INX",	"ICP.M.FR.N.080000.4.INX",	"ICP.M.FR.N.090000.4.INX",	"ICP.M.FR.N.100000.4.INX",	"ICP.M.FR.N.110000.4.INX",	"ICP.M.FR.N.120000.4.INX")

x<-get_data("ICP.M.FR.N.000000.4.INX",filter=list(startPeriod=2000,endPeriod=2022))
data=data.frame(as.Date(paste(x$obstime,1,sep="-"),"%Y-%m-%d"))

for (i in names){
  x<-get_data(i,filter=list(startPeriod=2000,endPeriod=2022))
  data<-cbind(data,x$obsvalue)
}

names(data)<-c('Date','HICP - Overall index',	'HICP - FOOD','HICP - ALCOHOL, TOBACCO','HICP - CLOTHING','HICP - ELECTRICITY, GAS','HICP - FURNISHINGS','HICP - HEALTH','HICP - TRANSPORT','HICP - COMMUNICATION','HICP - RECREATION	','HICP - EDUCATION	','HICP - RESTAURANTS','HICP - MISCELLANEOUS')

colnames(data) <- gsub('HICP - ', '', colnames(data), fixed=TRUE)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.
```{r}

d <- melt(data, id.vars="Date")
monthly<-d %>%
    group_by(variable) %>%
    mutate(VAL.IND = value/value[Date=="2000-01-01"])%>%
    mutate(Year=cut(Date,"year"))
  
log_month<- monthly %>%
  group_by(variable)%>%
  mutate(log_v=c(NA,diff(log(VAL.IND))))

annual<-monthly %>%
  group_by(Year, variable)%>%
  filter(row_number()==1)

log_annual<- annual %>%
  group_by(variable)%>%
  mutate(log_v=c(NA,diff(log(VAL.IND))))

ggplot(monthly, aes(x=Date,y=VAL.IND, col=variable)) + 
  geom_path()
ggplot(log_month, aes(x=Date,y=log_v, col=variable)) + 
  geom_path()

ggplot(annual, aes(x=Date,y=VAL.IND, col=variable)) + 
  geom_path()
ggplot(log_annual, aes(x=Date,y=log_v, col=variable)) + 
  geom_path()


```


```{r}
library(readxl)
average_con <- read_excel("average_con.xlsx", 
    sheet = "Sheet 1")

colnames(average_con)<-c("Date","Type","Value")
average_con[,1]<-as.Date(average_con$Date, "%Y")
average_con[,3]<-as.numeric(average_con$Value)

cons_per_decile <- read_excel("cons_per_decile.xlsx", 
    sheet = "Feuil1")
```


```{r}
average_con<-average_con %>% filter(Type!="Total")
average_con<-average_con %>% filter(Date!="2021-08-25")

average_con$Type <- sapply(average_con$Type, switch, 
                      "Food and non-alcoholic beverages"="FOOD",
                      "Alcoholic beverages, tobacco and narcotics"="ALCOHOL, TOBACCO",
                      "Clothing and footwear"="CLOTHING",
                      "Housing, water, electricity, gas and other fuels"="ELECTRICITY, GAS",
                      "Furnishings, household equipment and routine household maintenance"="FURNISHINGS",
                      "Health"="HEALTH",
                      "Transport"="TRANSPORT",
                      "Communications"="COMMUNICATION",
                      "Recreation and culture" ="RECREATION",
                      "Education"="EDUCATION",
                      "Restaurants and hotels"="RESTAURANTS",
                      "Miscellaneous goods and services"="MISCELLANEOUS",
)
   

average_con<-average_con %>%
  group_by(Type, y=cut(Date, "year"))%>%
  mutate(mean_val=mean(Value))


png(file="cons_average.png")              
ggplot(average_con, aes(fill=Type, y=Value, x=Date)) + 
  geom_bar(position="stack", stat="identity")+
  theme_bw()+
  labs(y="Share", title = "Consumption share average household")+
  scale_fill_brewer(palette="Set3")
dev.off()
```


```{r}
colnames(cons_per_decile)<-c("Type","income_grp","s_1999","s_2005","s_2010","s_2015")
d<-cons_per_decile %>%
    group_by(income_grp) %>%
    mutate(Somme_1999 = sum(s_1999), Somme_2005=sum(s_2005), Somme_2010=sum(s_2010), Somme_2015=sum(s_2015))

share<-d %>%
  group_by(income_grp) %>%
  summarize(Type=Type, s_1999/Somme_1999, s_2005/Somme_2005, s_2010/Somme_2010, s_2015/Somme_2015 )

colnames(share)<-c("income_grp","Type","s_1999","s_2005","s_2010","s_2015")
d <- melt(share, id.vars=c("Type","income_grp"))
d$variable <- gsub('s_', '', d$variable, fixed=TRUE)

colnames(d)<-c("Type", "income_grp", "Date", "Value")

d$Quintile <- sapply(d$income_grp, switch, 
                     "First quintile"=1,
                     "Second quintile"=2,
                     "Third quintile"=3,
                     "Fourth quintile"=4,
                     "Fifth quintile"=5,
)

d$Type <- sapply(d$Type, switch, 
                      "Food and non-alcoholic beverages"="FOOD",
                      "Alcoholic beverages, tobacco and narcotics"="ALCOHOL, TOBACCO",
                      "Clothing and footwear"="CLOTHING",
                      "Housing, water, electricity, gas and other fuels"="ELECTRICITY, GAS",
                      "Furnishings, household equipment and routine household maintenance"="FURNISHINGS",
                      "Health"="HEALTH",
                      "Transport"="TRANSPORT",
                      "Communications"="COMMUNICATION",
                      "Recreation and culture" ="RECREATION",
                      "Education"="EDUCATION",
                      "Miscellaneous goods and services"="MISCELLANEOUS",
)
quintile_exposure <- d[order(d$Quintile),]                                            
quintile_exposure$Date<-as.Date(quintile_exposure$Date, format='%Y')
quintile_exposure$Date <- sub('-08-27', '-01-01', quintile_exposure$Date, fixed=TRUE)
quintile_exposure$Date <- sub('1999', '2000', quintile_exposure$Date, fixed=TRUE)

```

```{r}
png("cons_per_quintile.png")
ggplot(d, aes(fill=Type, y=Value, x=Quintile)) + 
  geom_bar(position="stack", stat="identity")+
  facet_grid(~ Date)+
  theme_bw()+
  labs(y="Share","Consumption share over time per quintile", 
       title="Consumption share EA by quintile and year",
       caption = "Author's calculation, Eurostat consumption expenditure by income quintile and COICOP")+ 
  scale_y_continuous(labels = scales::percent)+
  scale_fill_brewer(palette="Paired")
dev.off()
```
Construct average weighted price index.

```{r}
colnames(log_annual)<-c("Date","Type","value","Valueindex","y","log_v")

pricequantity <- log_annual %>% right_join(average_con, by=c("Type","y"))

pq<-pricequantity %>%
  group_by(y) %>%
  mutate(exposure=sum(Valueindex*Value, na.rm=TRUE))

pq<-pq %>%
    group_by(Type)%>%
    mutate(exposure_average = exposure/exposure[Date.x=="2000-01-01"])

pq<-pq %>% filter(between(Date.x, as.Date('2000-01-01'), as.Date('2020-12-31')))

ggplot(pq, aes(x=Date.x,y=exposure_average, col=Type)) + 
  geom_path()
```


Construct per decile weighted price index.
```{r}
log_annual$Date<-as.character(log_annual$Date)
total_quintile<-log_annual %>% right_join(quintile_exposure, by=c("Date","Type"))

pq_quintile<-total_quintile %>%
  group_by(Date, income_grp) %>%
  mutate(exposure=sum(Valueindex*Value, na.rm=TRUE))

pq_quintile<-pq_quintile %>%
    group_by(income_grp)%>%
    mutate(exposure_average = exposure/exposure[Date=="2000-01-01"])

ggplot(pq_quintile, aes(x=as.Date(Date),y=exposure_average, col=income_grp)) + 
  geom_path()
```


